const data = {
  products: [
    {
      _id: "1",
      name: "Nike Dragon",
      category: "Shirts",
      image: "/images/snake-head.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 2,
      numReviews: 10,
      description: "high quality",
    },
    {
      _id: "2",
      name: "Adidas Dragon",
      category: "Shirts",
      image: "/images/snake-head.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality",
    },
    {
      _id: "3",
      name: "Rebok Dragon",
      category: "Shirts",
      image: "/images/snake-head.png",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality",
    },
    {
      _id: "4",
      name: "Just Dragon",
      category: "Shirts",
      image: "/images/snake-head.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      numReviews: 10,
      description: "high quality",
    },
    {
      _id: "4",
      name: "Just Dragon",
      category: "Shirts",
      image: "/images/snake-head.png",
      price: 120,
      countInStock: 12,
      brand: "Nike",
      rating: 0,
      numReviews: 10,
      description: "high quality",
    },
  ],
};

export default data;
